name: Masak-Mod
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'

      - name: Install Gradle & Build (Jalur Ninja)
        run: |
          # Kita pakai gradle sistem, bukan ./gradlew
          sudo apt-get update
          sudo apt-get install -y gradle
          gradle build

      - name: Upload Hasil Jadi
        uses: actions/upload-artifact@v4
        with:
          name: Mod-Astral-Hold
          path: build/libs/*.jar
