name: Masak-Mod
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'

      # OBAT PENGUAT: Bikin ulang si jantung Gradle sebelum build
      - name: Rebuild Gradle Wrapper
        run: |
          mkdir -p gradle/wrapper
          gradle wrapper --gradle-version 8.4
          chmod +x gradlew

      - name: Build Mod
        run: ./gradlew build

      - uses: actions/upload-artifact@v4
        with:
          name: Mod-Astral-Hold
          path: build/libs/*.jar
