name: Masak-Mod
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'
      
      # URUTAN HARUS BENER: Kasih izin dulu baru jalanin
      - name: Setup Gradle
        run: |
          chmod +x gradlew
          ./gradlew wrapper --gradle-version 8.4
          
      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build

      - uses: actions/upload-artifact@v4
        with:
          name: Mod-Astral-Hold
          path: build/libs/*.jar
